### PR TITLE
Fix c/_cffi_backend.c:15:17: fatal error

### PR DESCRIPTION
**Pull request by iamarya2k24**
Add libffi-dev dependency package.

### CODE REVIEW

**Comment by iamarya2k24** [comment]
Tested working on Raspberry Pi running Ubuntu 20.04 LTS Server.
